### PR TITLE
auto-pin power dice at end of round

### LINKED ISSUE #502: auto-pin power dice at end of round
it's easy to forget. It might make sense to have an intrusive modal show up to force you to choose the dice to keep (since that's kind of how it works in person), but as a start, auto-pinning power dice should be simpler and accomplish most of the goal

### PR DESCRIPTION
**Pull request by bdwain**
fix #502

### CODE REVIEW

**Review by danj3000 — CHANGES_REQUESTED** [review]
Alas this doesn't work. I think you need a player.setSelectedDice at the end

Take a look at allplayerdiscardprompt - line 39 it checks if the player has taken a discard (or has pinned in this case) to avoid weird selection / selectable highlights carrying over.

Finally, you can replace 'power' literal with Level.Power

**Comment by bdwain** [comment]
how's this?

**Comment by bdwain** [comment]
oops had to fix a typo

**Comment by danj3000** [comment]
It's not working for me. do you see the dice selected when you run a test game?

**Pull request closed without merging**
